### ISSUE TITLE
Travis Rules for ARMv7

### ISSUE THREAD

**Issue by suggestedfixes** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#440]
I wrote some CI rules for fun, I wonder if it's possible to include it. Travis rules:
```
    - name: "ARMv7"
      os: linux
      addons:
        apt:
          packages:
            - gcc-arm-linux-gnueabihf
            - g++-arm-linux-gnueabihf
            - binutils-arm-linux-gnueabihf
            - qemu-user-static
      compiler: gcc
      before_script:
        - export CC=arm-linux-gnueabihf-gcc CXX=arm-linux-gnueabihf-g++
        - mkdir build && cd build
        - cmake .. -DBUILD_OPENSSL=TRUE -DBUILD_OPENSSL_PLATFORM=linux-generic32 -DBUILD_LIBSRTP_HOST_PLATFORM=x86_64-unknown-linux-gnu -DBUILD_LIBSRTP_DESTINATION_PLATFORM=arm-unknown-linux-uclibcgnueabihf -DBUILD_TEST=TRUE
      script:
        - make
        - export QEMU_LD_PREFIX=/usr/arm-linux-gnueabihf
        - timeout --signal=SIGABRT 40m ./tst/webrtc_client_test
```
